from services import *
from constants import *

build_plot_distribution_of_length(HAM_MESSAGES_OUTPUT_FILENAME, HAM_MESSAGES_LENGTH_PLOT_FILENAME)
build_plot_distribution_of_length(SPAM_MESSAGES_OUTPUT_FILENAME, SPAM_MESSAGES_LENGTH_PLOT_FILENAME)
build_plot_distribution_of_length(HAM_WORDS_OUTPUT_FILENAME, HAM_WORDS_LENGTH_PLOT_FILENAME)
build_plot_distribution_of_length(SPAM_WORDS_OUTPUT_FILENAME, SPAM_WORDS_LENGTH_PLOT_FILENAME)

build_plot_most_frequent_words(
    HAM_WORDS_STAT_OUTPUT_FILENAME, MOST_FREQUENT_HAM_WORDS_PLOT_FILENAME)
build_plot_most_frequent_words(
    SPAM_WORDS_STAT_OUTPUT_FILENAME, MOST_FREQUENT_SPAM_WORDS_PLOT_FILENAME)
